version: "3.8"

services:
  web:
    environment:
      NODE_ENV: development
      RAILS_ENV: production
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
    build:
      context: .
      args:
        USER_ID: 1000
        GROUP_ID: 1000
        APP_DIR: /app

    command: bash -c "rm -f tmp/pids/server.pid &&
      ./bin/webpack-dev-server &
      bundle exec rails server puma -p 3000 -b '0.0.0.0'"

    volumes:
      - .:/app

    ports:
      - "3000:3000"
